#!/bin/bash

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
NORMAL=$(tput sgr0)
UNDERLINE=$(tput smul)
BRIGHT=$(tput bold)

if [ -f /etc/light-default.conf ]; then
    :
else
    printf "default color conf missing\nmaking conf\n\n"
    sudo touch /etc/light-default.conf
fi

if [ -f /etc/light-current.conf ]; then
    :
else
    printf "current color file missing\nmaking conf\n\n"
    sudo touch /etc/light-current.conf
fi

while getopts ih:s:d: option; do
  case $option in
    i)
      printf "/bin/light                                script wrapper"
      printf "/bin/light.py                             light interface"
      printf "/etc/systemd/system/light.service         light service"
      printf "/lib/systemd/system-sleep/light.sleep     sleep script"
      printf "/bin/light.start                          light service script"
      printf "/etc/light-current.conf                   light current state"
      printf "/etc/light-default.conf                   light default state"
      printf "/bin/lightscript                          script"
      ;;
    h)
      printf "${UNDERLINE}${BRIGHT}colors:${NORMAL}${RED}\nred${GREEN}\ngreen${BLUE}\nblue${YELLOW}\nyellow${MAGENTA}\nmagenta${CYAN}\ncyan${WHITE}\nwhite${WHITE}\nblack\n${NORMAL}"
      printf "${UNDERLINE}${BRIGHT}\ncommands:\n${NORMAL}"
      printf "set color:           light -s [color]\n"
      printf "set default color:   light -d [color]\n"
      printf "see script paths:    light -i\n"
      printf "get this menu:       light -h\n"
      ;;
    s)
      sudo python /bin/light.py $2
      printf "color set to ${2}\n"
      sudo echo "${2}" | sudo tee >/etc/light-current.conf
      ;;
    d)
      sudo echo "${2}" | sudo tee >/etc/light-default.conf
      ;; 
  esac
done
